Algoritmo "Questao1"
// Disciplina   : Lógica de Programação
// Professora   : Tatyane Calixto
// Autora    : Tatyane Calixto
// Data atual  : 26/05/2022
Var
resultado,cotacao_dolar,valor_dolar:real

Inicio

escreval("Digite o valor da cotação em dólar: ")
leia(cotacao_dolar)
escreval("Digite o valor em dólar: ")
leia(valor_dolar)
resultado <- cotacao_dolar * valor_dolar
escreva("Resultado: R$",resultado)

Fimalgoritmo